# This workflow will do a clean install of node dependencies, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

env:
  LOG_LEVEL: debug
  HOME_ASSISTANT_URL: ""
  HOME_ASSISTANT_TOKEN: ""

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Check types
        run: npm run check:types
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
